name: CMake

on: [push, pull_request]

permissions:
  contents: read

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          build_python_bindings: ON
          use_asan: ON
        - os: windows-latest
          build_python_bindings: OFF
          use_asan: OFF
        - os: macos-latest
          build_python_bindings: OFF
          use_asan: OFF

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-python@v7
      with:
        python-version: '3.x'

    - name: Install CMake 4.4
      run: python -m pip install cmake==4.4.0

    - name: Install Python test dependencies
      if: matrix.build_python_bindings == 'ON'
      run: python -m pip install pytest numpy scipy POT

    - name: Install optional tools (clang-tidy)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y clang-tidy

    - name: Enable clang-tidy problem matcher
      if: matrix.os == 'ubuntu-latest'
      run: echo "::add-matcher::.github/clang-tidy-matcher.json"

    - name: Install Conan
      run: python -m pip install "conan>=2.0"

    - name: Conan Profile Detect
      run: conan profile detect --force

    - name: Install dependencies with Conan
      run: conan install . --build=missing -s build_type=Release

    - name: Configure CMake
      run: cmake --preset conan-release -DEMDGRID_BUILD_PYTHON_BINDINGS=${{ matrix.build_python_bindings }} -DUSE_ASAN=${{ matrix.use_asan }} .

    - name: Build
      run: cmake --build --preset conan-release

    - name: Test
      run: ctest --preset conan-release --output-on-failure
