name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          build_python_bindings: ON
        - os: windows-latest
          build_python_bindings: OFF
        - os: macos-latest
          build_python_bindings: OFF

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install optional tools (clang-tidy)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y clang-tidy

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DEMDGRID_BUILD_PYTHON_BINDINGS=${{ matrix.build_python_bindings }} .

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
